# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 751011de1259969629c6de43839b8eb060733c7c915b5ea96d356769682c6c265b2f27ce8f321c261908e5111689d5f7925d7be04e59db635310c27c0f6da481

test:
  secret_key_base: 6feb04dbb8094d368a44ce9ccdeb95f4aa473538e46ac0a6ffb71da6dac5ae142634aded1d291f2074119df93712f8fdec5ddadcfc8cafcfbe88b6517590ec31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
